### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by bsr203** [shortbloke/DogDoor#7]
Hi.
I am new to Arduino, and learning from your project. I see usage of `Log` throughout the code, but don't see an import. Which library do you use? I am also looking for a good logger than outputting to serial.

Thanks. 
bsr

**Comment by shortbloke** [comment]
I'm using a Particle Photon for this project which provides the Log instance of the Logger class: https://docs.particle.io/reference/device-os/firmware/photon/#logging-levels

**Comment by bsr203** [comment]
Thanks. While searching I found https://embeddedartistry.com/blog/2019/12/30/arduino-logging-library/
look very thought out. will give it a try. thanks again. Cheers
